use_frameworks!

platform :ios, '10.0'

target 'EDMPMQTTClient_Example' do
  pod 'EDMPMQTTClient', :path => '../'

  target 'EDMPMQTTClient_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
